# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@score_docs_as_code//:docs.bzl", "docs_bundle")

docs_bundle(
    name = "kvs_docs",
    code_targets = [
        ":kvs_cpp",
        "//score/kvs/rust_kvs:rust_kvs",
    ],
    primary_need_id = "comp__persistency_kvs",
    source_dir = "docs",
    visibility = ["//visibility:public"],
)

# The filegroup is used to collect all source files for the tests.

cc_library(
    name = "kvsvalue",
    srcs = [
        "kvsvalue.cpp",
    ],
    hdrs = ["kvsvalue.hpp"],
    includes = ["."],
    visibility = [
        "//visibility:public",
    ],
)

cc_library(
    name = "kvs_cpp",
    srcs = [
        "kvs.cpp",
        "kvsbuilder.cpp",
    ],
    hdrs = [
        "kvs.hpp",
        "kvsbuilder.hpp",
    ],
    implementation_deps = [
        "//score/kvs/internal:kvs_helper",
    ],
    includes = ["."],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":kvsvalue",
        "//score/kvs/internal:error",
        "@score_baselibs//score/filesystem",
        "@score_baselibs//score/json",
        "@score_baselibs//score/mw/log",
        "@score_baselibs//score/result",
    ],
)
